setup(name=' package_name',
      version='0.1',
      url='https://github.com/denisavilamontini/Projeto',
      license='GPL-3.0 License',
      author='Denis Avila Montini',
      author_email='denisavilamontini@yahoo.com.br',
      description='Add static script_dir() method to Path',
      packages=find_packages(exclude=['tests']),
      long_description=open('README.md').read(),
      zip_safe=False)